name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2016
            visual_studio: "Visual Studio 15 2017"


    steps:
    - uses: actions/checkout@v2
    - name: cmake version
      shell: bash
      run: cmake --version
   
      
    - name: CloneITK
      run: git clone https://github.com/InsightSoftwareConsortium/ITK.git ${{github.workspace}}/ITK
    - name: ConfigITK
      run: cmake ${{github.workspace}}/ITK -B ${{github.workspace}}/build_itk -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/itk_install
    - name: BuildITK
      run: cmake --build -B ${{github.workspace}}/build_itk --target install --config ${{env.BUILD_TYPE}}
    - name: ListITK
      run: dir ${{github.workspace}}/itk_install
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DITK_DIR=${{github.workspace}}/itk_install/lib/cmake/ITK-5.3/
      
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
